; ascii characters
 ascii_space                            = 32
 ascii_pling                            = 33
 ascii_00                               = 48
 ascii_01                               = 49
 ascii_02                               = 50
 ascii_03                               = 51
 ascii_04                               = 52
 ascii_05                               = 53
 ascii_06                               = 54
 ascii_07                               = 55
 ascii_08                               = 56
 ascii_09                               = 57

 ascii_under_score                      = 60
 ascii_equals                           = 61
 ascii_greater_than                     = 62
 ascii_upper_a                          = 65
 ascii_upper_z                          = 90
 ascii_a                                = 97
 ascii_z                                = 122

; ascii top bit set codes
 bit_ascii_space                        = 32 + &80
 bit_ascii_pling                        = 33 + &80
 bit_ascii_00                           = 48 + &80
 bit_ascii_01                           = 49 + &80
 bit_ascii_02                           = 50 + &80
 bit_ascii_03                           = 51 + &80
 bit_ascii_04                           = 52 + &80
 bit_ascii_05                           = 53 + &80
 bit_ascii_06                           = 54 + &80
 bit_ascii_07                           = 55 + &80
 bit_ascii_08                           = 56 + &80
 bit_ascii_09                           = 57 + &80
 bit_ascii_semi_colon                   = 59 + &80
 bit_ascii_less_than                    = 60 + &80
 bit_ascii_greater_than                 = 62 + &80
 bit_ascii_a                            = 65 + &80
 bit_ascii_b                            = 66 + &80
 bit_ascii_c                            = 67 + &80
 bit_ascii_d                            = 68 + &80
 bit_ascii_e                            = 69 + &80
 bit_ascii_f                            = 70 + &80
 bit_ascii_g                            = 71 + &80
 bit_ascii_h                            = 72 + &80
 bit_ascii_i                            = 73 + &80
 bit_ascii_j                            = 74 + &80
 bit_ascii_k                            = 75 + &80
 bit_ascii_l                            = 76 + &80
 bit_ascii_m                            = 77 + &80
 bit_ascii_n                            = 78 + &80
 bit_ascii_o                            = 79 + &80
 bit_ascii_p                            = 80 + &80
 bit_ascii_q                            = 81 + &80
 bit_ascii_r                            = 82 + &80
 bit_ascii_s                            = 83 + &80
 bit_ascii_t                            = 84 + &80
 bit_ascii_u                            = 85 + &80
 bit_ascii_v                            = 86 + &80
 bit_ascii_w                            = 87 + &80
 bit_ascii_x                            = 88 + &80
 bit_ascii_y                            = 89 + &80
 bit_ascii_z                            = 90 + &80
 bit_ascii_under_score                  = 95 + &80
